# Generated by Django 5.1.4 on 2025-01-30 18:34

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='connection_type',
            field=models.CharField(choices=[('42', '42 School API'), ('github', 'Github API'), ('regular', 'Our Own Auth')], default='regular', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'connection_type')},
        ),
    ]
